'use client';
import {FormEvent,useState} from 'react';
const euro=new Intl.NumberFormat('it-IT',{style:'currency',currency:'EUR',maximumFractionDigits:0});
type Contract='indeterminato'|'determinato'; type CityKey='milano'|'roma'|'napoli'|'bologna'|'torino';
type City={name:string;region:string;regionalLabel:string;municipalLabel:string;regionalSource:string;municipalSource:string;regional:(n:number)=>number;municipal:(n:number)=>number};
function progressive(n:number,b:Array<[number,number]>){let tax=0,from=0;for(const[to,rate]of b){tax+=Math.max(0,Math.min(n,to)-from)*rate;from=to}return tax}
const cities:Record<CityKey,City>={
milano:{name:'Milano',region:'Lombardia',regionalLabel:'1,23% · 1,58% · 1,72% · 1,73%',municipalLabel:'0,8% oltre 23.000 €',regionalSource:'https://www.regione.lombardia.it/bollo-auto-e-tributi-regionali/red-addizionale-regionale-irpef',municipalSource:'https://www1.finanze.gov.it/finanze2/dipartimentopolitichefiscali/fiscalitalocale/nuova_addcomirpef/risultato.htm?anno=9999&cc=F205&pr=MI&r=1',regional:n=>progressive(n,[[15000,.0123],[28000,.0158],[50000,.0172],[Infinity,.0173]]),municipal:n=>n>23000?n*.008:0},
roma:{name:'Roma',region:'Lazio',regionalLabel:'1,73% fino a 28.000 €; poi 1,73% / 3,33%',municipalLabel:'0,9% oltre 14.000 €',regionalSource:'https://consiglio.regione.lazio.it/consiglio-regionale/?id=9524&sv=vigente&vw=leggiregionalidettaglio',municipalSource:'https://www1.finanze.gov.it/finanze2/dipartimentopolitichefiscali/fiscalitalocale/nuova_addcomirpef/risultato.htm?anno=9999&cc=H501&pr=RM&r=1',regional:n=>n<=28000?n*.0173:Math.max(0,progressive(n,[[15000,.0173],[Infinity,.0333]])-(n<=30000?60:0)),municipal:n=>n>14000?n*.009:0},
napoli:{name:'Napoli',region:'Campania',regionalLabel:'1,73% · 2,96% · 3,20% · 3,33%',municipalLabel:'1,0% oltre 12.000 €',regionalSource:'https://entrate.regione.campania.it/it/addizionale-irpef',municipalSource:'https://www1.finanze.gov.it/finanze2/dipartimentopolitichefiscali/fiscalitalocale/nuova_addcomirpef/risultato.htm?anno=9999&cc=F839&pr=NA&r=1',regional:n=>progressive(n,[[15000,.0173],[28000,.0296],[50000,.032],[Infinity,.0333]]),municipal:n=>n>12000?n*.01:0},
bologna:{name:'Bologna',region:'Emilia-Romagna',regionalLabel:'1,33% · 1,93% · 2,78% · 3,33%',municipalLabel:'0,8% oltre 15.000 €',regionalSource:'https://finanze.regione.emilia-romagna.it/tributi-regionali/imposte/addizionale-irpef/quanto-come-e-quando-si-paga',municipalSource:'https://www1.finanze.gov.it/finanze2/dipartimentopolitichefiscali/fiscalitalocale/nuova_addcomirpef/risultato.htm?anno=9999&cc=A944&pr=BO&r=1',regional:n=>progressive(n,[[15000,.0133],[28000,.0193],[50000,.0278],[Infinity,.0333]]),municipal:n=>n>15000?n*.008:0},
torino:{name:'Torino',region:'Piemonte',regionalLabel:'1,62% · 2,68% · 3,31% · 3,33%',municipalLabel:'0,8% · 0,8% · 1,1% · 1,2%; esente fino a 11.790 €',regionalSource:'https://www.regione.piemonte.it/web/media/53597/download',municipalSource:'https://www1.finanze.gov.it/finanze2/dipartimentopolitichefiscali/fiscalitalocale/nuova_addcomirpef/risultato.htm?anno=9999&cc=L219&pr=TO&r=1',regional:n=>progressive(n,[[15000,.0162],[28000,.0268],[50000,.0331],[Infinity,.0333]]),municipal:n=>n>11790?progressive(n,[[15000,.008],[28000,.008],[50000,.011],[Infinity,.012]]):0}};
function workDeduction(n:number,c:Contract){if(n<=15000)return Math.max(1955,c==='determinato'?1380:690);if(n<=28000)return 1910+1190*((28000-n)/13000);if(n<=50000)return 1910*((50000-n)/22000)+(n>=25000&&n<=35000?65:0);return 0}
function extraDeduction(n:number){if(n>20000&&n<=32000)return 1000;if(n>32000&&n<=40000)return 1000*((40000-n)/8000);return 0}
function taxFree(n:number){if(n>20000)return 0;if(n<=8500)return n*.071;if(n<=15000)return n*.053;return n*.048}
function calculate(ral:number,months:number,contract:Contract,cityKey:CityKey){const city=cities[cityKey],contributions=ral*.0919+Math.max(0,ral-56224)*.01,taxable=Math.max(0,ral-contributions),gross=progressive(taxable,[[28000,.23],[50000,.33],[Infinity,.43]]),work=Math.min(gross,workDeduction(taxable,contract)),extra=Math.min(Math.max(0,gross-work),extraDeduction(taxable)),irpef=Math.max(0,gross-work-extra),regional=irpef>0?city.regional(taxable):0,municipal=irpef>0?city.municipal(taxable):0,bonus=taxFree(taxable),taxes=irpef+regional+municipal,net=ral-contributions-taxes+bonus;return{ral,months,contract,cityKey,contributions,taxable,gross,work,extra,irpef,regional,municipal,bonus,taxes,net,monthly:net/months,effective:ral?(contributions+taxes-bonus)/ral*100:0}}
type Result=ReturnType<typeof calculate>;
function Row({label,value,detail,tone='negative'}:{label:string;value:number;detail?:string;tone?:'negative'|'positive'|'neutral'}){return <div className="breakdown-row"><div><span>{label}</span>{detail&&<small>{detail}</small>}</div><strong className={tone}>{tone==='negative'?'− ':tone==='positive'?'+ ':''}{euro.format(value)}</strong></div>}
export default function Home(){const[input,setInput]=useState('35000'),[months,setMonths]=useState(13),[contract,setContract]=useState<Contract>('indeterminato'),[cityKey,setCityKey]=useState<CityKey>('milano'),[result,setResult]=useState<Result>(()=>calculate(35000,13,'indeterminato','milano')),[error,setError]=useState('');
function submit(e:FormEvent){e.preventDefault();const ral=Number(input.replace(',','.'));if(!Number.isFinite(ral)||ral<5000||ral>300000){setError('Inserisci una RAL tra 5.000 € e 300.000 €.');return}setError('');setResult(calculate(ral,months,contract,cityKey))}
const city=cities[cityKey],rc=cities[result.cityKey],netShare=Math.max(0,Math.min(100,result.net/result.ral*100)),contribShare=result.contributions/result.ral*100,taxShare=result.taxes/result.ral*100;
return <main><nav className="nav shell"><a className="brand" href="#top"><span className="brand-mark">J</span><span>Jet HR</span></a><span className="prototype-pill">Prototipo · Regole 2026</span></nav>
<section className="hero shell" id="top"><div className="hero-copy"><p className="eyebrow">RAL → NETTO</p><h1>Quanto ti resta<br/>davvero?</h1><p className="lede">Una stima chiara della tua retribuzione netta, con ogni trattenuta spiegata.</p><div className="assumption-line"><span>{city.name}</span><span>Tempo {contract}</span><span>Senza familiari a carico</span></div></div>
<form className="calculator-card" onSubmit={submit}><div className="card-heading"><div><p className="eyebrow">LA TUA RETRIBUZIONE</p><h2>Partiamo dalla RAL</h2></div><span className="status-dot"/></div>
<label htmlFor="ral">Retribuzione annua lorda</label><div className={'money-input '+(error?'invalid':'')}><span>€</span><input id="ral" inputMode="decimal" value={input} onChange={e=>setInput(e.target.value)}/><small>all’anno</small></div><p className={error?'error':'hint'}>{error||'Inserisci l’importo lordo indicato nella proposta o nel contratto.'}</p>
<fieldset><legend>Tipologia di contratto</legend><div className="contract-toggle">{(['indeterminato','determinato'] as Contract[]).map(v=><button type="button" key={v} className={contract===v?'active':''} onClick={()=>setContract(v)}>Tempo {v}</button>)}</div><p className="field-note">Nel caso annuale standard il contratto non cambia il netto; cambia la detrazione minima nei rapporti brevi.</p></fieldset>
<fieldset><legend>Città di residenza</legend><div className="city-grid">{(Object.keys(cities) as CityKey[]).map(k=><button type="button" key={k} className={cityKey===k?'active':''} onClick={()=>setCityKey(k)}><strong>{cities[k].name}</strong><small>{cities[k].region}</small></button>)}</div><p className="field-note">La città determina addizionale regionale e comunale.</p></fieldset>
<fieldset><legend>Mensilità previste</legend><div className="month-toggle">{[12,13,14].map(v=><button type="button" key={v} className={months===v?'active':''} onClick={()=>setMonths(v)}>{v}</button>)}</div></fieldset><button className="calculate-button">Calcola il netto <span>→</span></button><p className="privacy-note">Nessun account richiesto. Nessun dato viene salvato o inviato.</p></form></section>
<section className="results-wrap" aria-live="polite"><div className="shell results-grid"><div className="results-summary"><p className="eyebrow light">LA TUA STIMA · {rc.name.toUpperCase()}</p><h2>{euro.format(result.net)}</h2><p className="annual-label">netti all’anno</p><div className="monthly-result"><span>{euro.format(result.monthly)}</span><small>netti × {result.months} mensilità</small></div><div className="rate"><span>Incidenza trattenute</span><strong>{result.effective.toFixed(1).replace('.',',')}%</strong></div><div className="salary-bar"><span className="bar-net" style={{width:netShare+'%'}}/><span className="bar-contributions" style={{width:contribShare+'%'}}/><span className="bar-taxes" style={{width:taxShare+'%'}}/></div><div className="legend"><span><i className="net"/>Netto</span><span><i className="contrib"/>Contributi</span><span><i className="tax"/>Imposte</span></div></div>
<div className="breakdown-card"><div className="breakdown-title"><div><p className="eyebrow">DAL LORDO AL NETTO</p><h3>Tutte le voci</h3></div><span>Annuale</span></div><Row label="Retribuzione lorda (RAL)" value={result.ral} tone="neutral"/><Row label="Contributi INPS" value={result.contributions} detail="9,19% + 1% oltre la soglia"/><div className="subtotal"><span>Imponibile fiscale</span><strong>{euro.format(result.taxable)}</strong></div><Row label="IRPEF netta" value={result.irpef} detail={'Imposta lorda '+euro.format(result.gross)+' − detrazioni '+euro.format(result.work+result.extra)}/><Row label="Addizionale regionale" value={result.regional} detail={'Regione '+rc.region+' · '+rc.regionalLabel}/><Row label="Addizionale comunale" value={result.municipal} detail={rc.name+' · '+rc.municipalLabel}/>{result.bonus>0&&<Row label="Somma esente lavoro dipendente" value={result.bonus} tone="positive"/>}<div className="net-total"><span>Netto annuale stimato</span><strong>{euro.format(result.net)}</strong></div></div></div></section>
<section className="method shell"><div className="method-heading"><p className="eyebrow">DIETRO AL NUMERO</p><h2>Un calcolo trasparente,<br/>non una scatola nera.</h2></div><div className="method-grid"><article><span>01</span><h3>Contributi previdenziali</h3><p>9,19% a carico del dipendente, più l’1% sulla quota oltre 56.224 €. L’extra NASpI del determinato è a carico dell’azienda.</p></article><article><span>02</span><h3>IRPEF progressiva</h3><p>Scaglioni 2026 al 23%, 33% e 43%, meno le detrazioni da lavoro dipendente.</p></article><article><span>03</span><h3>Imposte locali</h3><p>Regione e Comune cambiano con la città scelta. Regole regionali 2026 e ultimo dato comunale pubblicato, il 2025.</p></article></div>
<details className="assumptions"><summary>Assunzioni e limiti del prototipo <span>+</span></summary><div><p>Stima per l’intero 2026, impiegato privato residente tutto l’anno nella città scelta, senza familiari a carico, altri redditi, bonus, premi, deduzioni o agevolazioni.</p><p>Il tipo di contratto cambia la detrazione minima nei rapporti brevi. Assumendo 365 giorni, la detrazione ordinaria è già superiore e i due contratti danno normalmente lo stesso netto. Risultato orientativo.</p></div></details>
<div className="sources"><p className="eyebrow">FONTI PRINCIPALI</p><a href="https://www.gazzettaufficiale.it/atto/serie_generale/caricaArticoloDefault/originario?atto.codiceRedazionale=25G00212&atto.dataPubblicazioneGazzetta=2025-12-30&atto.tipoProvvedimento=LEGGE" target="_blank" rel="noreferrer">Legge di Bilancio 2026 ↗</a><a href="https://www.inps.it/it/it/inps-comunica/atti/circolari-messaggi-e-normativa/dettaglio.circolari-e-messaggi.2026.01.circolare-numero-6-del-30-01-2026_15151.html" target="_blank" rel="noreferrer">INPS n. 6/2026 ↗</a><a href={rc.regionalSource} target="_blank" rel="noreferrer">Addizionale {rc.region} ↗</a><a href={rc.municipalSource} target="_blank" rel="noreferrer">Addizionale {rc.name} ↗</a></div></section>
<footer><div className="shell"><span className="brand footer-brand"><span className="brand-mark">J</span>Jet HR</span><p>Prototipo dimostrativo · Agosto 2026</p></div></footer></main>}

